name: Release Workflow
on:
  workflow_dispatch: {}

jobs:
 release:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Checkout Code with Ref '${{ github.ref }}'
        uses: actions/checkout@v2


      - name: Build Project
        run: npn install

      - name: Create '.npmrc' File 
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: npm publish
